export const equipos = [
  {
    id: 1,
    code: 'DE',
    nombre: 'Alemania',
    confederacion: 'UEFA',
    pos: 'E3',
    rank: 1650.53,
  },
  {
    id: 2,
    code: 'SA',
    nombre: 'Arabia Saudita',
    confederacion: 'AFC',
    pos: 'C2',
    rank: 1444.69,
  },
  {
    id: 3,
    code: 'AR',
    nombre: 'Argentina',
    confederacion: 'CONMEBOL',
    pos: 'C1',
    rank: 1765.13,
  },
  {
    id: 4,
    code: 'BR',
    nombre: 'Brasil',
    confederacion: 'CONMEBOL',
    pos: 'G1',
    rank: 1823.69,
  },
  {
    id: 5,
    code: 'BE',
    nombre: 'Bélgica',
    confederacion: 'UEFA',
    pos: 'F1',
    rank: 1827,
  },
  {
    id: 6,
    code: 'CM',
    nombre: 'Camerún',
    confederacion: 'CAF',
    pos: 'G4',
    rank: 1480.48,
  },
  {
    id: 7,
    code: 'CA',
    nombre: 'Canadá',
    confederacion: 'CONCACAF',
    pos: 'F2',
    rank: 1479,
  },
  {
    id: 8,
    code: 'KR',
    nombre: 'Corea del Sur',
    confederacion: 'AFC',
    pos: 'H4',
    rank: 1519.54,
  },
  {
    id: 9,
    code: 'HR',
    nombre: 'Croacia',
    confederacion: 'UEFA',
    pos: 'F4',
    rank: 1621.11,
  },
  {
    id: 10,
    code: 'DK',
    nombre: 'Dinamarca',
    confederacion: 'UEFA',
    pos: 'D3',
    rank: 1653.6,
  },
  {
    id: 11,
    code: 'EC',
    nombre: 'Ecuador',
    confederacion: 'CONMEBOL',
    pos: 'A2',
    rank: 1452.63,
  },
  {
    id: 12,
    code: 'ES',
    nombre: 'España',
    confederacion: 'UEFA',
    pos: 'E1',
    rank: 1709.19,
  },
  {
    id: 13,
    code: 'US',
    nombre: 'Estados Unidos',
    confederacion: 'CONCACAF',
    pos: 'B3',
    rank: 1633.72,
  },
  {
    id: 14,
    code: 'FR',
    nombre: 'Francia',
    confederacion: 'UEFA',
    pos: 'D1',
    rank: 1789.85,
  },
  {
    id: 15,
    code: 'GH',
    nombre: 'Ghana',
    confederacion: 'CAF',
    pos: 'H2',
    rank: 1387.36,
  },
  {
    id: 16,
    code: 'NL',
    nombre: 'Holanda',
    confederacion: 'UEFA',
    pos: 'A4',
    rank: 1658.66,
  },
  {
    id: 17,
    code: 'EN',
    nombre: 'Inglaterra',
    confederacion: 'UEFA',
    pos: 'B1',
    rank: 1761.71,
  },
  {
    id: 18,
    code: 'IR',
    nombre: 'Irán',
    confederacion: 'AFC',
    pos: 'B2',
    rank: 1564.49,
  },
  {
    id: 19,
    code: 'JP',
    nombre: 'Japón',
    confederacion: 'AFC',
    pos: 'E4',
    rank: 1553.44,
  },
  {
    id: 20,
    code: 'MA',
    nombre: 'Marruecos',
    confederacion: 'CAF',
    pos: 'F3',
    rank: 1551.88,
  },
  {
    id: 21,
    code: 'MX',
    nombre: 'México',
    confederacion: 'CONCACAF',
    pos: 'C3',
    rank: 1658.82,
  },
  {
    id: 22,
    code: 'PL',
    nombre: 'Polonia',
    confederacion: 'UEFA',
    pos: 'C4',
    rank: 1544.2,
  },
  {
    id: 23,
    code: 'PT',
    nombre: 'Portugal',
    confederacion: 'UEFA',
    pos: 'H1',
    rank: 1674.78,
  },
  {
    id: 24,
    code: 'QA',
    nombre: 'Qatar',
    confederacion: 'AFC',
    pos: 'A1',
    rank: 1441.41,
  },
  {
    id: 25,
    code: 'SN',
    nombre: 'Senegal',
    confederacion: 'CAF',
    pos: 'A3',
    rank: 1584.16,
  },
  {
    id: 26,
    code: 'RS',
    nombre: 'Serbia',
    confederacion: 'UEFA',
    pos: 'G2',
    rank: 1547.53,
  },
  {
    id: 27,
    code: 'CH',
    nombre: 'Suiza',
    confederacion: 'UEFA',
    pos: 'G3',
    rank: 1635.32,
  },
  {
    id: 28,
    code: 'TN',
    nombre: 'Túnez',
    confederacion: 'CAF',
    pos: 'D4',
    rank: 1499.8,
  },
  {
    id: 29,
    code: 'UY',
    nombre: 'Uruguay',
    confederacion: 'CONMEBOL',
    pos: 'H3',
    rank: 1635.73,
  },
  {
    id: 30,
    code: 'CR',
    nombre: 'Costa Rica *',
    confederacion: 'CONCACAF',
    pos: 'E2',
    rank: 1503.09,
  },
  {
    id: 31,
    code: 'wa',
    nombre: 'Gales *',
    confederacion: 'UEFA',
    pos: 'B4',
    rank: 1588.08,
  },
  {
    id: 32,
    code: 'PE',
    nombre: 'Perú *',
    confederacion: 'CONMEBOL',
    pos: 'D2',
    rank: 1562.32,
  },
];
/* 
  { id: 30, code: 'PE', nombre: "Perú", confederacion: "CONMEBOL", pos: "D2", rank: 1562.32 },
  { id: 30, code: 'AU', nombre: "Australia", confederacion: "CONMEBOL", pos: "D2", rank: 1462.29 },
  { id: 30, code: 'AE', nombre: "Emiratos", confederacion: "CONMEBOL", pos: "D2", rank: 1356.99 },

  { id: 30, code: 'UA', nombre: "Ucrania", confederacion: "CONCACAF", pos: "B4", rank: 1535.08 },
  { id: 30, code: 'SC', nombre: "Escocia", confederacion: "CONCACAF", pos: "B4", rank: 1472.66 },
  { id: 30, code: 'WA', nombre: "Gales", confederacion: "CONCACAF", pos: "B4", rank: 1588.08 },
  
  { id: 30, code: 'NZ', nombre: "Nueva Zelanda", confederacion: "CONCACAF", pos: "E2", rank: 1206.07 },
  { id: 30, code: 'CR', nombre: "Costa Rica", confederacion: "CONCACAF", pos: "E2", rank: 1503.09 },
  
   
*/
